package com.hse.userservice.domain.ledger;

public enum LedgerEntryType {
    DEPOSIT, WITHDRAWAL, BOOKING_CHARGE, CANCELLATION_REFUND, DAY_CLOSURE_COMPENSATION, MEMBERSHIP_BLOCK_COMPENSATION, MANUAL_CREDIT, MANUAL_DEBIT, SERVICE_REQUEST_CHARGE
}
