package com.hse.adminservice.entity;

public enum Grant {
    COWORKING_LIST,
    COWORKING_CREATE,
    COWORKING_VIEW,
    COWORKING_EDIT,
    COWORKING_ARCHIVE,
    COWORKING_DASHBOARD_VIEW,
    ACCESS_VIEW,
    ACCESS_MANAGE,
    ROLE_VIEW,
    ROLE_ASSIGN,
    PLACE_VIEW,
    PLACE_MANAGE
}
