spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration,classpath:db/demo

integration.admin-service.base-url=${ADMIN_SERVICE_BASE_URL:http://localhost:8081/api}
integration.internal-api.key=${INTERNAL_API_KEY:apwDJG/HFraFNhiVs+jB6OiTy/iST+S6JrEM2iksXh50vHn3tihJ1lG7K7sh/4ESxYPkK8VGhYioNb2gHk9FaQ==}

app.jwt.secret=${USER_JWT_SECRET:2JwOpQqjjaqPeDmw49YYmBb1burnfcBBqtrRc3CUn9y2KryJ74SOMWeJFQJ5IGJPanMaIpIxV3TuXjJ5/I6f0Q==}
