CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    coworking_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    blocked_at TIMESTAMP,
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT uk_membership_user_coworking UNIQUE (user_id, coworking_id),
    CONSTRAINT ck_membership_status CHECK (status IN ('PENDING', 'ACTIVE', 'BLOCKED'))
);
CREATE INDEX idx_memberships_coworking_created ON user_memberships (coworking_id, created_at DESC);
CREATE INDEX idx_memberships_user_created ON user_memberships (user_id, created_at DESC);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    place_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    date DATE NOT NULL,
    cost BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(32) NOT NULL,
    booking_number VARCHAR(32) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    tariff_id BIGINT NOT NULL,
    price_per_day BIGINT NOT NULL,
    full_refund_hours_before INTEGER NOT NULL,
    late_cancellation_refund_percent INTEGER NOT NULL,
    cancellation_compensation_coefficient NUMERIC(10,4) NOT NULL,
    day_closure_compensation_coefficient NUMERIC(10,4) NOT NULL,
    membership_block_compensation_coefficient NUMERIC(10,4) NOT NULL,
    CONSTRAINT fk_bookings_membership FOREIGN KEY (membership_id) REFERENCES user_memberships(id) ON DELETE CASCADE,
    CONSTRAINT ck_booking_status CHECK (status IN ('ACTUAL', 'CANCELED_ADMIN', 'CANCELED_USER')),
    CONSTRAINT ck_booking_cost_non_negative CHECK (cost >= 0),
    CONSTRAINT ck_booking_late_refund_range CHECK (late_cancellation_refund_percent BETWEEN 0 AND 100),
    CONSTRAINT uk_booking_number UNIQUE (booking_number)
);
CREATE UNIQUE INDEX uk_booking_active_place_date ON bookings (place_id, date) WHERE active = TRUE;
CREATE INDEX idx_bookings_membership_date ON bookings (membership_id, date DESC);
CREATE INDEX idx_bookings_place_date ON bookings (place_id, date);
CREATE INDEX idx_bookings_request_id ON bookings (request_id);
CREATE SEQUENCE IF NOT EXISTS booking_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    reference_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    comment VARCHAR(1000),
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT fk_ledger_membership FOREIGN KEY (membership_id) REFERENCES user_memberships(id) ON DELETE CASCADE,
    CONSTRAINT ck_ledger_type CHECK (type IN (
        'BALANCE_TOP_UP', 'BALANCE_WITHDRAWAL',
        'BOOKING_CHARGE', 'BOOKING_USER_CANCELLATION_REFUND',
        'BOOKING_ADMIN_CANCELLATION_COMPENSATION',
        'MANUAL_CREDIT', 'MANUAL_DEBIT', 'SERVICE_REQUEST_CHARGE'
    )),
    CONSTRAINT ck_ledger_amount_non_zero CHECK (amount <> 0),
    CONSTRAINT uk_ledger_membership_type_reference UNIQUE (membership_id, type, reference_id)
);
CREATE INDEX idx_ledger_membership_timestamp ON ledger_entries (membership_id, timestamp DESC);

CREATE TABLE pay_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    user_comment VARCHAR(1000),
    admin_comment VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pay_requests_membership FOREIGN KEY (membership_id) REFERENCES user_memberships(id) ON DELETE CASCADE,
    CONSTRAINT ck_pay_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_pay_request_amount_non_zero CHECK (amount <> 0)
);
CREATE INDEX idx_pay_requests_membership_created ON pay_requests (membership_id, created_at DESC);
CREATE INDEX idx_pay_requests_status ON pay_requests (status);

CREATE TABLE user_service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    type_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    cost BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_service_requests_membership FOREIGN KEY (membership_id) REFERENCES user_memberships(id) ON DELETE CASCADE,
    CONSTRAINT ck_service_request_status CHECK (status IN ('NEW', 'IN_PROGRESS', 'RESOLVED', 'REJECTED')),
    CONSTRAINT ck_service_request_cost_non_negative CHECK (cost >= 0)
);
CREATE INDEX idx_service_requests_membership_created ON user_service_requests (membership_id, created_at DESC);
CREATE INDEX idx_service_requests_status ON user_service_requests (status);

CREATE TABLE request_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT NOT NULL,
    author_type VARCHAR(16) NOT NULL,
    author_id BIGINT,
    text VARCHAR(1000),
    timestamp TIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    CONSTRAINT fk_request_messages_service_request FOREIGN KEY (service_request_id) REFERENCES user_service_requests(id) ON DELETE CASCADE,
    CONSTRAINT ck_request_message_author_type CHECK (author_type IN ('USER', 'ADMIN', 'SYSTEM'))
);
CREATE INDEX idx_request_messages_request_timestamp ON request_messages (service_request_id, timestamp);

CREATE TABLE request_message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    file_id VARCHAR(500) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_request_attachments_message FOREIGN KEY (message_id) REFERENCES request_messages(id) ON DELETE CASCADE,
    CONSTRAINT ck_request_attachment_size_non_negative CHECK (size_bytes >= 0)
);
CREATE INDEX idx_request_attachments_message ON request_message_attachments (message_id);
CREATE SEQUENCE IF NOT EXISTS manual_adjustment_reference_seq START WITH 1 INCREMENT BY 1;
