CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_admins_email UNIQUE (email)
);

CREATE TABLE coworkings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    address VARCHAR(500) NOT NULL,
    working_hours_label VARCHAR(255) NOT NULL,
    hero_title VARCHAR(255),
    hero_text VARCHAR(2000),
    image_urls_json TEXT NOT NULL,
    image_file_ids_json TEXT NOT NULL,
    schedule INTEGER NOT NULL,
    owner_id BIGINT NOT NULL,
    auto_approve_membership BOOLEAN NOT NULL,
    floor_map_enabled BOOLEAN,
    join_token VARCHAR(36),
    is_active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    configuration_version BIGINT NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_coworkings_join_token UNIQUE (join_token)
);

CREATE TABLE tariffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price_per_day BIGINT NOT NULL,
    full_refund_hours_before INTEGER NOT NULL,
    late_cancellation_refund_percent INTEGER NOT NULL,
    cancellation_compensation_coefficient NUMERIC(10,4) NOT NULL,
    day_closure_compensation_coefficient NUMERIC(10,4) NOT NULL,
    membership_block_compensation_coefficient NUMERIC(10,4) NOT NULL,
    tariff_version INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_tariffs_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT uk_tariff_coworking_name_archived UNIQUE (coworking_id, name, archived),
    CONSTRAINT ck_tariff_price_non_negative CHECK (price_per_day >= 0),
    CONSTRAINT ck_tariff_late_refund_range CHECK (late_cancellation_refund_percent BETWEEN 0 AND 100)
);
CREATE INDEX idx_tariffs_coworking ON tariffs (coworking_id);

CREATE TABLE floors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    floor_index INTEGER NOT NULL,
    image_file_id VARCHAR(500),
    full_image_file_id VARCHAR(500),
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_floors_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT uk_floor_coworking_index_archived UNIQUE (coworking_id, floor_index, archived)
);
CREATE INDEX idx_floors_coworking ON floors (coworking_id);

CREATE TABLE place_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    tariff_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_place_types_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT fk_place_types_tariff FOREIGN KEY (tariff_id) REFERENCES tariffs(id),
    CONSTRAINT uk_place_type_coworking_name_archived UNIQUE (coworking_id, name, archived)
);
CREATE INDEX idx_place_types_coworking ON place_types (coworking_id);
CREATE INDEX idx_place_types_tariff ON place_types (tariff_id);

CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    floor_id BIGINT NOT NULL,
    place_type_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    loc_x NUMERIC(10,4),
    loc_y NUMERIC(10,4),
    image_file_id VARCHAR(500),
    preview_image_file_id VARCHAR(500),
    full_image_file_id VARCHAR(500),
    amenities_raw VARCHAR(1000),
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_places_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT fk_places_floor FOREIGN KEY (floor_id) REFERENCES floors(id) ON DELETE CASCADE,
    CONSTRAINT fk_places_place_type FOREIGN KEY (place_type_id) REFERENCES place_types(id),
    CONSTRAINT uk_place_floor_name_archived UNIQUE (floor_id, name, archived)
);
CREATE INDEX idx_places_coworking ON places (coworking_id);
CREATE INDEX idx_places_floor ON places (floor_id);
CREATE INDEX idx_places_place_type ON places (place_type_id);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    grants_raw VARCHAR(2000) NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_roles_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT uk_role_coworking_name UNIQUE (coworking_id, name)
);
CREATE INDEX idx_roles_coworking ON roles (coworking_id);

CREATE TABLE access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    coworking_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_access_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT uk_access_admin_coworking UNIQUE (admin_id, coworking_id)
);
CREATE INDEX idx_access_admin ON access (admin_id);
CREATE INDEX idx_access_coworking ON access (coworking_id);

CREATE TABLE coworking_schedule_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    exception_date DATE NOT NULL,
    type VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_schedule_exceptions_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT uk_coworking_schedule_exception_unique UNIQUE (coworking_id, exception_date, archived),
    CONSTRAINT ck_schedule_exception_type CHECK (type IN ('OPEN', 'CLOSE'))
);
CREATE INDEX idx_schedule_exceptions_coworking_date ON coworking_schedule_exceptions (coworking_id, exception_date);

CREATE TABLE place_closings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    closing_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_place_closings_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT fk_place_closings_place FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE,
    CONSTRAINT uk_place_closing_unique UNIQUE (place_id, closing_date, archived)
);
CREATE INDEX idx_place_closings_coworking_date ON place_closings (coworking_id, closing_date);
CREATE INDEX idx_place_closings_place_date ON place_closings (place_id, closing_date);

CREATE TABLE service_request_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coworking_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    cost BIGINT NOT NULL,
    type_version INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_service_request_types_coworking FOREIGN KEY (coworking_id) REFERENCES coworkings(id) ON DELETE CASCADE,
    CONSTRAINT uk_service_request_type_coworking_name_archived UNIQUE (coworking_id, name, archived),
    CONSTRAINT ck_service_request_type_cost_non_negative CHECK (cost >= 0)
);
CREATE INDEX idx_service_request_types_coworking ON service_request_types (coworking_id);
