package com.hse.adminservice.rbac.entity;

public enum Grant {
    COWORKING_READ, COWORKING_EDIT, FLOOR_READ, FLOOR_EDIT, PLACE_TYPE_READ, PLACE_TYPE_EDIT, PLACE_READ, PLACE_EDIT, TARIFF_READ, TARIFF_EDIT, SERVICE_REQUEST_TYPE_READ, SERVICE_REQUEST_TYPE_EDIT, ROLE_READ, ROLE_EDIT, ACCESS_READ, ACCESS_EDIT, SCHEDULE_READ, SCHEDULE_EDIT, USER_READ, USER_EDIT, BOOKING_READ, BOOKING_EDIT
}
